# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 14:24
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventari',
            old_name='unit_price',
            new_name='cmimi_per_njesi',
        ),
        migrations.RenameField(
            model_name='inventari',
            old_name='code',
            new_name='kodi',
        ),
        migrations.RenameField(
            model_name='inventari',
            old_name='description',
            new_name='pershkrim',
        ),
        migrations.RemoveField(
            model_name='inventari',
            name='cetagory',
        ),
        migrations.RemoveField(
            model_name='inventari',
            name='name',
        ),
        migrations.RemoveField(
            model_name='inventari',
            name='supplier',
        ),
        migrations.AddField(
            model_name='inventari',
            name='cmimi_shitjes',
            field=models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20),
        ),
        migrations.AddField(
            model_name='inventari',
            name='gjendje',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='inventari',
            name='permasat',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
