# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-21 15:04
from __future__ import unicode_literals

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20180621_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='Furnizimi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_porosise', models.DateTimeField(auto_now_add=True)),
                ('cmimi_per_njesi', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('sasia', models.IntegerField(blank=True, max_length=200, null=True)),
                ('cmimi_total', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('pershkrim', models.TextField(blank=True, null=True)),
                ('permasat', models.IntegerField(blank=True, max_length=200, null=True)),
                ('kodiF', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kodiF', to='management.Inventari')),
            ],
        ),
        migrations.CreateModel(
            name='Klienti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emer', models.CharField(max_length=50)),
                ('mbiemer', models.CharField(max_length=50)),
                ('nrTel', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shitje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sasia', models.IntegerField(blank=True, max_length=200, null=True)),
                ('ulje', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('cmimi_per_njesi', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('cmimi_shitjes', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('pershkrim', models.TextField(blank=True, null=True)),
                ('kapari', models.DecimalField(decimal_places=4, default=Decimal('0.0000'), max_digits=20)),
                ('data_porosise', models.DateTimeField(auto_now_add=True)),
                ('data_dorezimit', models.DateTimeField()),
                ('klienti', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='klienti', to='management.Klienti')),
                ('kodiS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='kodiS', to='management.Inventari')),
            ],
        ),
    ]
